before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
language: ruby
rvm:
- 2.2.3
deploy:
  provider: heroku
  app:
    master: safe-taiga-82373
  api_key:
    secure: pzr2BGzgXtxcCyR1uaqzRcfC1hYLWKvsMjExV+DEfp/yuQ4CTcwy8NeMkodF2Zodf8KLBwU5b0jXMPnKdMf4z1qEBEEg2qUXXfC2QlXeKWLZLxBoPYkK6ozMt2TLSgzm1Jz0nMuaJGwEft8+q5VawI5Oq6BOpaqn3ubBaWSh/G/afaKJcZZPkbCyLkNLxHbX3LDM62ptMdBnvspkSoT5Cp5Tz2lBudustUeEvetPDb9jXVKCu1EjK8xUJTdvC4rnoTinWFZA2mD7UeJ6Fws++evIWhctA1FqeNV0pPBNftndYwXlbALTbMpNqc32n9oGR7uKrLvQ89daR/1Y7EG2PrD/EFVIPQ+y1lo2CRgrzt4mxdFjPUwSRF7dNctYw6G0SN9Cxdd9KzbAQbLNfNES330xj0/LKeihwIu/Bwc+iPDv0C65K6aliaYY+l6alhlL25tXQX1NEziF6n27lHkqqfPUxk55z7v/lYMw/3/3qvy4iWMCyXGYXM4ncnbDHRADYHB8cjIfxX99xoZURndjxbwi5Y6x5R5C+UIr/ErYBRvxbaet3EW7b8jFPAnT+BhNsO75fCPykRx3EWEewjeO1XZcinuxsJIpK0Emm+1/iO9QjP+K1pAbagowKHWoPlntx3a+jtnvyPvzuYcLQYUXWNRqA0GDdfcSTRvHi/VZrK8=
